import { initializeApp } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js";
import { getAuth, createUserWithEmailAndPassword, signInWithEmailAndPassword, signOut, onAuthStateChanged } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js";
import { getFirestore, collection, addDoc, getDocs, doc, getDoc, setDoc, serverTimestamp } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js";
import { firebaseConfig } from "./firebase-config.js";
const app=initializeApp(firebaseConfig), auth=getAuth(app), db=getFirestore(app);
window.register=async()=>{try{const n=document.getElementById("name").value,e=document.getElementById("email").value,p=document.getElementById("password").value;const c=await createUserWithEmailAndPassword(auth,e,p);await setDoc(doc(db,"users",c.user.uid),{name:n,email:e,balance:0,createdAt:serverTimestamp()});location.href="jobs.html"}catch(x){alert(x.message)}};
window.login=async()=>{try{await signInWithEmailAndPassword(auth,email.value,password.value);location.href="jobs.html"}catch(x){alert(x.message)}};
window.logout=async()=>{await signOut(auth);location.href="index.html"};
async function loadJobs(){const box=document.getElementById("jobs");if(!box)return;const s=await getDocs(collection(db,"jobs"));box.innerHTML="";s.forEach(d=>{const j=d.data();box.innerHTML+=`<article class="card"><h2>${j.title}</h2><p>${j.description||""}</p><b>Reward Rp ${Number(j.reward||0).toLocaleString("id-ID")}</b><br><a class="btn" href="job.html?id=${d.id}">Lihat tugas</a></article>`})}
async function loadJob(){const p=new URLSearchParams(location.search),id=p.get("id");if(!id)return;const d=await getDoc(doc(db,"jobs",id));if(!d.exists())return;const j=d.data();document.getElementById("title").textContent=j.title;document.getElementById("desc").textContent=j.description||"";document.getElementById("reward").textContent="Rp "+Number(j.reward||0).toLocaleString("id-ID");document.getElementById("rules").innerHTML=(j.rules||[]).map(x=>`<li>${x}</li>`).join("");window.submitTask=async()=>{const u=auth.currentUser;if(!u)return alert("Silakan login.");await addDoc(collection(db,"submissions"),{jobId:id,userId:u.uid,proof:document.getElementById("proof").value,status:"pending",createdAt:serverTimestamp()});alert("Terkirim. Menunggu pemeriksaan admin.")}}
window.addJob=async()=>{if(auth.currentUser?.uid!==(await import("./firebase-config.js")).ADMIN_UID)return alert("Bukan admin");await addDoc(collection(db,"jobs"),{title:jobTitle.value,reward:Number(jobReward.value),description:jobDesc.value,rules:["Ikuti instruksi tugas.","Kirim hasil yang benar dan dapat diverifikasi.","Dilarang meminta atau membagikan password, OTP, atau data rahasia."],createdAt:serverTimestamp()});alert("Tugas ditambahkan.")};
onAuthStateChanged(auth,async u=>{const el=document.getElementById("user");if(el&&u){el.textContent=u.email;const d=await getDoc(doc(db,"users",u.uid));if(d.exists())document.getElementById("balance").textContent=Number(d.data().balance||0).toLocaleString("id-ID")}});loadJobs();loadJob();